Models/ErrorViewModel.cs
namespace projetoinicial_mvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;

namespace projetoinicial_mvc.Controllers
{
    public class CalculadoraController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Soma(int valor1, int valor2)
        {
            var total = valor1 + valor2;
            return Ok(total); 
        }
        public IActionResult Subtracao(int valor1, int valor2)
        {
            var total = valor1 - valor2;
            return Ok(total);
        }
        public IActionResult Multiplicacao(int valor1, int valor2)
        {
            var total = valor1 * valor2;
            return Ok(total);
        }
        public IActionResult Divisao(int valor1, int valor2)
        {
            var total = valor1 / valor2;
            return Ok(total);
        }
    }

}

Controllers/CidadeController.cs
using Microsoft.AspNetCore.Mvc;

namespace projetoinicial_mvc.Controllers
{
    public class CidadeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using projetoinicial_mvc.Models;

namespace projetoinicial_mvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Calculadora/Index.cshtml
<b>CALCULADORA</b>
<h1 style="font-size:x-large"> Primeiro valor: </h1>
<input type="number" id="valor1" />
<h2 style="font-size:x-large"> Segundo Valor: </h2>
<input type="number" id="valor2"/>
<h3 style="font-size:x-large"> Operação </h3>
<button onclick="soma()">+</button>
<button onclick="Subtracao()">-</button>
<button onclick="Divisao()">/</button>
<button onclick="Multiplicacao()">*</button>
<h4>Resultado: </h4>
<input type="number" id="total" />

Views/Cidade/Index.cshtml
<h1 style="color: green; font-weight:bold"> ARTUR BORGES</h1>
<h2 style="font-weight:bold;"> ARTUR BORGES</h2>
<h3 style="color: red"> ARTUR BORGES</h3>
<h4 class="minha_classe"> ARTUR BORGES</h4>
<h5> ARTUR BORGES</h5>
<h6> ARTUR BORGES</h6>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projetoinicial_mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projetoinicial_mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">projetoinicial_mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cidade" asp-action="Index">Cidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - projetoinicial_mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>